name: Docker functionality 
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Docker
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: echo test
