/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/imprint': RouteRecordInfo<'/imprint', '/imprint', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/post/[id]': RouteRecordInfo<'/post/[id]', '/post/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/privacy-policy': RouteRecordInfo<'/privacy-policy', '/privacy-policy', Record<never, never>, Record<never, never>>,
    '/prmrs/forest-project/': RouteRecordInfo<'/prmrs/forest-project/', '/prmrs/forest-project', Record<never, never>, Record<never, never>>,
    '/prmrs/forest-project/create': RouteRecordInfo<'/prmrs/forest-project/create', '/prmrs/forest-project/create', Record<never, never>, Record<never, never>>,
    '/progress-logs/': RouteRecordInfo<'/progress-logs/', '/progress-logs', Record<never, never>, Record<never, never>>,
    '/progress-logs/create': RouteRecordInfo<'/progress-logs/create', '/progress-logs/create', Record<never, never>, Record<never, never>>,
    '/team/': RouteRecordInfo<'/team/', '/team', Record<never, never>, Record<never, never>>,
    '/team/create': RouteRecordInfo<'/team/create', '/team/create', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/[...404].vue': {
      routes: '/[...404]'
      views: never
    }
    'src/pages/about.vue': {
      routes: '/about'
      views: never
    }
    'src/pages/imprint.vue': {
      routes: '/imprint'
      views: never
    }
    'src/pages/login.vue': {
      routes: '/login'
      views: never
    }
    'src/pages/post/[id].vue': {
      routes: '/post/[id]'
      views: never
    }
    'src/pages/privacy-policy.vue': {
      routes: '/privacy-policy'
      views: never
    }
    'src/pages/prmrs/forest-project/index.vue': {
      routes: '/prmrs/forest-project/'
      views: never
    }
    'src/pages/prmrs/forest-project/create.vue': {
      routes: '/prmrs/forest-project/create'
      views: never
    }
    'src/pages/progress-logs/index.vue': {
      routes: '/progress-logs/'
      views: never
    }
    'src/pages/progress-logs/create.vue': {
      routes: '/progress-logs/create'
      views: never
    }
    'src/pages/team/index.vue': {
      routes: '/team/'
      views: never
    }
    'src/pages/team/create.vue': {
      routes: '/team/create'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
