name: CD - Docker

on:
  push:
    branches: [main, master]

jobs:
  docker:
    name: "Image"
    environment: Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dummy Step
        run: echo "This is a dummy job that always succeeds"
