name: CI - API

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main, master]

defaults:
  run:
    working-directory: api

jobs:
  format:
    name: "Format"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Format
        run: cargo fmt --all
  lint:
    name: "Lint"
    needs: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Clippy
        run: cargo clippy --fix
  type-check:
    name: "Type Check"
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Check
        run: cargo check
