name: CI - Functionality

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main, master]

jobs:
  docker:
    name: "Docker deployment"
    environment: Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Dummy Step
        run: echo "This is a dummy job that always succeeds"
