name: CI - Functionality 

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  docker:
    name: "Docker deployment"
    environment: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Dummy Step
        run: echo "This is a dummy job that always succeeds"
