name: CI - Frontend

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main, master]

defaults:
  run:
    working-directory: frontend

jobs:
  format:
    environment: Build
    name: "Format"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        name: Use pnpm ${{ vars.PNPM_VERSION }}
        with:
          version: ${{ vars.PNPM_VERSION }}
          run_install: false
      - name: Use Node.js ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ vars.NODE_VERSION }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Format
        run: pnpm run format
  lint:
    environment: Build
    name: "Lint"
    needs: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        name: Use pnpm ${{ vars.PNPM_VERSION }}
        with:
          version: ${{ vars.PNPM_VERSION }}
          run_install: false
      - name: Use Node.js ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ vars.NODE_VERSION }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: ESLint
        run: pnpm run lint
  type-check:
    environment: Build
    name: "Type Check"
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        name: Use pnpm ${{ vars.PNPM_VERSION }}
        with:
          version: ${{ vars.PNPM_VERSION }}
          run_install: false
      - name: Use Node.js ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ vars.NODE_VERSION }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Check
        run: pnpm run type-check
