name: CI - Frontend

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main, master]

defaults:
  run:
    working-directory: frontend

jobs:
  type-check:
    name: "Type Check"
    runs-on: ubuntu-latest
    steps:
      - name: Dummy Step
        run: echo "This is a dummy job that always succeeds"
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - name: Dummy Step
        run: echo "This is a dummy job that always succeeds"
  format:
    name: "Format"
    runs-on: ubuntu-latest
    steps:
      - name: Dummy Step
        run: echo "This is a dummy job that always succeeds"
