name: CI - Frontend

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  type-check:
    name: "Type Check"
    runs-on: ubuntu-latest
    steps:
      - name: Dummy Step
        run: echo "This is a dummy job that always succeeds"
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - name: Dummy Step
        run: echo "This is a dummy job that always succeeds"
  format:
    name: "Format"
    runs-on: ubuntu-latest
    steps:
      - name: Dummy Step
        run: echo "This is a dummy job that always succeeds"
