name: CI - Frontend

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main, master]

defaults:
  run:
    working-directory: frontend

env:
  NODE_VERSION: "20.x"
  PNPM_VERSION: "9"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Use pnpm ${{ env.PNPM_VERSION }}
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: ll
        run: ls -l
      - name: pnpm
        run: |
          pnpm install
          pnpm help install
  format:
    name: "Format"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Use pnpm ${{ env.PNPM_VERSION }}
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Format
        run: pnpm run format
  lint:
    name: "Lint"
    needs: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Use pnpm ${{ env.PNPM_VERSION }}
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: ESLint
        run: pnpm run lint
  type-check:
    name: "Type Check"
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Use pnpm ${{ env.PNPM_VERSION }}
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Check
        run: pnpm run type-check
